// Central UI copy catalogue. Replace this object (or select another locale object)
// to translate the dashboard without changing component logic.
export const uiText = {
  common: {
    loading: "Chargement…",
    sticker: (count = 1) => `sticker${count > 1 ? "s" : ""}`,
    album: (count = 1) => `album${count > 1 ? "s" : ""}`,
    stickerFallback: (number) => `Sticker ${number}`,
    stickerNumber: (number) => `N° ${number}`,
    percentageCompleted: (percentage) => `${percentage}% complété`,
    countryLabel: (country) => `Pays : ${country}`,
    collected: "Collecté",
    missing: "Manquant",
    obtainedOn: (date) => `Obtenu le ${date}`,
    openAlbum: "Voir l’album",
  },
  navigation: {
    ariaLabel: "Albums Tour de France",
    collection: "Collection",
    coming: "À venir",
    search: "Rechercher dans la collection",
  },
  messages: {
    albumEyebrow: "Album Panini",
    collectionEyebrow: "Collection Panini",
    albumLoadError: "Impossible de charger l’album",
    collectionLoadError: "Impossible de charger la collection",
    riderLoadError: "Impossible de charger le coureur",
    albumIndexError: "Index des albums introuvable",
    snapshotsError: "Aucun snapshot trouvé",
    albumDataError: (title) => `Impossible de charger ${title}`,
  },
  search: {
    eyebrow: "Recherche",
    collectionEyebrow: "Toute la collection",
    title: "Rechercher un sticker",
    intro: "Retrouvez un sticker par son nom, dans tous vos albums.",
    fieldLabel: "Nom du sticker",
    placeholder: "Ex. Pogačar",
    prompt: "Saisissez un nom pour commencer.",
    noResults: (query) => `Aucun sticker trouvé pour « ${query} ».`,
    resultCount: (count) => `${count} résultat${count > 1 ? "s" : ""}`,
    albums: (count) => count > 1 ? "Albums" : "Album",
    albumOccurrence: (year, number) => `${year} (N° ${number})`,
    collectedCount: (count) => `${count} collecté${count > 1 ? "s" : ""}`,
    openLatestAlbum: "Voir le dernier album",
  },
  rider: {
    eyebrow: "Fiche coureur",
    back: "Retour à la recherche",
    noAppearances: "Aucune apparition connue.",
    collectionStage: "Dans la collection",
    appearances: "Apparitions",
    collectedOn: (date) => `Collecté le ${date}`,
  },
  collection: {
    eyebrow: "Ma collection Panini",
    title: "Tour de France",
    intro: "Tous les albums, une seule ligne d’arrivée.",
    total: "au total",
    summaryLabel: "Résumé de la collection",
    albums: "albums",
    completed: "terminés",
    collected: "collectés",
    missing: "manquants",
    peloton: "Le peloton",
    myAlbums: "Mes albums",
    equalWeight: "Chaque année compte autant",
    notStarted: "Pas commencé",
    finishedOn: "Terminé le",
    startedOn: "Commencé le",
    ownedOfTotal: (owned, total) => `${owned} sur ${total} stickers`,
    openAlbum: "Ouvrir l’album",
    hallStage: "Hall of Fame",
    hallTitle: "All-time Top 10",
    selectedOfTen: (count) => `${count} sur 10 sélectionnés`,
    emptyHallTitle: "Le podium attend ses légendes",
    emptyHallText: "Ajoutez jusqu’à 10 références dans",
  },
  rankings: {
    nations: "Les nations",
    countriesTitle: "Top 5 pays",
    countriesSubtitle: "Stickers de coureurs collectés",
    regulars: "Les habitués",
    ridersTitle: "Top 5 multi-albums",
    ridersSubtitle: "Nombre d’albums où le coureur est collecté",
  },
  album: {
    completed: "complété",
    collectionStage: "Étape de collection",
    collectedOfTotal: (owned, total) => `${owned} sur ${total} stickers collectés`,
    packetsOpened: (count) => `${count} paquets ouverts`,
    start: "Départ",
    finish: "Champs-Élysées",
    collectionHistory: "Évolution de la collection",
    gainSince: (gain, date) => `${gain >= 0 ? "+" : ""}${gain} stickers depuis le ${date}`,
    progressChartLabel: "Progression du pourcentage de stickers collectés",
    chartPoint: (date, percentage, owned, total) => `${date}: ${percentage}% (${owned} sur ${total})`,
    lastUpdate: "Dernière mise à jour",
    progress: "Progression",
    bestDay: "Meilleure journée",
    duplicatesHistory: "Évolution des doubles",
    duplicatesLatest: (count) => `${count} doubles au dernier snapshot`,
    duplicatesChartLabel: "Évolution du nombre de doubles",
    duplicatePoint: (date, count) => `${date}: ${count} doubles`,
    currentDuplicates: "Doubles actuels",
    sinceStart: "Depuis le départ",
    duplicatesCount: (count) => `${count} doubles`,
    yellowJersey: "Maillot jaune",
    inAlbum: "dans l'album",
    sprint: "Sprint",
    leftToChase: "encore à chasser",
    excludingInstants: (count) => `${count} hors instantanés`,
    mountain: "Montagne",
    duplicatesToTrade: "doubles à échanger",
    youngRider: "Jeune coureur",
    markedFavourites: "favoris marqués",
    chase: "À chasser",
    missingCount: (count) => `${count} sticker${count > 1 ? "s" : ""} manquant${count > 1 ? "s" : ""}`,
    collectedOfTotalShort: (owned, total) => `${owned} sur ${total} collectés`,
    sinceDate: (date) => `depuis le ${date}`,
    albumPodium: "Podium de l’album",
    favouriteCards: "Mes cartes préférées",
    personalTopThree: "Top 3 personnel",
    mensRanking: "Classement hommes",
    mensRankingSubtitle: "Top 3 des équipes hommes par stickers collectés",
    womensRanking: "Classement femmes",
    womensRankingSubtitle: "Top 3 des équipes femmes par stickers collectés",
    comingTitle: "Bientôt sur la ligne de départ",
    comingAlt: "Cycliste gravissant une route de montagne",
    comingText: "Cette collection est au programme. Son suivi apparaîtra ici dès que le premier snapshot sera ajouté.",
  },
  countries: {
    AUS: "Australie", AUT: "Autriche", BEL: "Belgique", BRA: "Brésil",
    CAN: "Canada", COL: "Colombie", CZE: "Tchéquie", DEN: "Danemark",
    ECU: "Équateur", ERI: "Érythrée", ESP: "Espagne", FRA: "France",
    GBR: "Royaume-Uni", GER: "Allemagne", HUN: "Hongrie", IRL: "Irlande",
    ITA: "Italie", KAZ: "Kazakhstan", LAT: "Lettonie", LVA: "Lettonie",
    MEX: "Mexique", MRI: "Maurice", NED: "Pays-Bas", NOR: "Norvège",
    NZL: "Nouvelle-Zélande", POL: "Pologne", POR: "Portugal", SUI: "Suisse",
    SVN: "Slovénie", USA: "États-Unis",
  },
};
