// Central UI copy catalogue. Replace this object (or select another locale object)
// to translate the dashboard without changing component logic.
const frenchText = {
  language: { label: "Langue", french: "Français", english: "Anglais", pageTitle: "Collection Panini" },
  common: {
    loading: "Chargement…",
    sticker: (count = 1) => `sticker${count > 1 ? "s" : ""}`,
    album: (count = 1) => `album${count > 1 ? "s" : ""}`,
    stickerFallback: (number) => `Sticker ${number}`,
    stickerNumber: (number) => `N° ${number}`,
    percentageCompleted: (percentage) => `${percentage}% complété`,
    countryLabel: (country) => `Pays : ${country}`,
    collected: "Collecté",
    missing: "Manquant",
    obtainedOn: (date) => `Obtenu le ${date}`,
    openAlbum: "Voir l’album",
    openFullSize: "Afficher l’image en taille réelle",
    fullSizeImage: "Image en taille réelle",
    closeFullSize: "Fermer l’image",
  },
  navigation: {
    ariaLabel: "Albums Tour de France",
    collection: "Collection",
    coming: "À venir",
    search: "Rechercher dans la collection",
  },
  messages: {
    albumEyebrow: "Album Panini",
    collectionEyebrow: "Collection Panini",
    albumLoadError: "Impossible de charger l’album",
    collectionLoadError: "Impossible de charger la collection",
    riderLoadError: "Impossible de charger le coureur",
    countryLoadError: "Impossible de charger le pays",
    albumIndexError: "Index des albums introuvable",
    snapshotsError: "Aucun snapshot trouvé",
    albumDataError: (title) => `Impossible de charger ${title}`,
  },
  search: {
    eyebrow: "Recherche",
    collectionEyebrow: "Toute la collection",
    title: "Rechercher un sticker ou un pays",
    intro: "Retrouvez un sticker par son nom ou explorez les coureurs d’un pays.",
    fieldLabel: "Nom du sticker ou pays",
    placeholder: "Ex. Pogačar ou France",
    prompt: "Saisissez un nom ou un pays pour commencer.",
    noResults: (query) => `Aucun sticker trouvé pour « ${query} ».`,
    resultCount: (count) => `${count} résultat${count > 1 ? "s" : ""}`,
    albums: (count) => count > 1 ? "Albums" : "Album",
    albumOccurrence: (year, number) => `${year} (N° ${number})`,
    collectedCount: (count) => `${count} collecté${count > 1 ? "s" : ""}`,
    openLatestAlbum: "Voir le dernier album",
    country: "Pays",
    countryStickerCount: (count) => `${count} sticker${count > 1 ? "s" : ""} de coureurs`,
    openCountry: "Voir le pays",
  },
  rider: {
    eyebrow: "Fiche coureur",
    back: "Retour à la recherche",
    noAppearances: "Aucune apparition connue.",
    collectionStage: "Dans la collection",
    appearances: "Apparitions",
    collectedOn: (date) => `Collecté le ${date}`,
    favourite: "Coureur favori",
  },
  country: {
    eyebrow: "Fiche pays",
    back: "Retour à la collection",
    summary: (count) => `${count} sticker${count > 1 ? "s" : ""} de coureurs dans la collection`,
    noStickers: "Aucun sticker de coureur connu.",
    collectionStage: "Dans la collection",
    stickers: "Coureurs",
    picturesOnly: "Avec photo uniquement",
    noPictures: "Aucun sticker avec photo pour ce pays.",
  },
  collection: {
    eyebrow: "Ma collection Panini",
    title: "Tour de France",
    intro: "Tous les albums, une seule ligne d’arrivée.",
    total: "au total",
    summaryLabel: "Résumé de la collection",
    albums: "albums",
    completed: "terminés",
    collected: "collectés",
    missing: "manquants",
    peloton: "Le peloton",
    myAlbums: "Mes albums",
    equalWeight: "Chaque année compte autant",
    notStarted: "Pas commencé",
    finishedOn: "Terminé le",
    startedOn: "Commencé le",
    ownedOfTotal: (owned, total) => `${owned} sur ${total} stickers`,
    openAlbum: "Ouvrir l’album",
    hallStage: "Hall of Fame",
    hallTitle: "All-time Top 10",
    selectedOfTen: (count) => `${count} sur 10 sélectionnés`,
    emptyHallTitle: "Le podium attend ses légendes",
    emptyHallText: "Ajoutez jusqu’à 10 références dans",
  },
  export: {
    button: "PDF",
    collectedStickers: "Stickers collectés",
    inventory: "Inventaire",
    updates: "mises à jour",
  },
  rankings: {
    nations: "Les nations",
    countriesTitle: "Top 5 pays",
    countriesSubtitle: "Stickers de coureurs collectés",
    regulars: "Les habitués",
    ridersTitle: "Top 5 multi-albums",
    ridersSubtitle: "Nombre d’albums où le coureur est collecté",
  },
  album: {
    completed: "complété",
    collectionStage: "Étape de collection",
    collectedOfTotal: (owned, total) => `${owned} sur ${total} stickers collectés`,
    packetsOpened: (count) => `${count} paquets ouverts`,
    start: "Départ",
    finish: "Champs-Élysées",
    collectionHistory: "Évolution de la collection",
    gainSince: (gain, date) => `${gain >= 0 ? "+" : ""}${gain} stickers depuis le ${date}`,
    progressChartLabel: "Progression du pourcentage de stickers collectés",
    chartPoint: (date, percentage, owned, total) => `${date}: ${percentage}% (${owned} sur ${total})`,
    lastUpdate: "Dernière mise à jour",
    progress: "Progression",
    bestDay: "Meilleure journée",
    duplicatesHistory: "Évolution des doubles",
    duplicatesLatest: (count) => `${count} doubles au dernier snapshot`,
    duplicatesChartLabel: "Évolution du nombre de doubles",
    duplicatePoint: (date, count) => `${date}: ${count} doubles`,
    currentDuplicates: "Doubles actuels",
    sinceStart: "Depuis le départ",
    duplicatesCount: (count) => `${count} doubles`,
    yellowJersey: "Maillot jaune",
    inAlbum: "dans l'album",
    sprint: "Sprint",
    leftToChase: "encore à chasser",
    excludingInstants: (count) => `${count} hors instantanés`,
    mountain: "Montagne",
    duplicatesToTrade: "doubles à échanger",
    youngRider: "Jeune coureur",
    markedFavourites: "favoris marqués",
    chase: "À chasser",
    missingCount: (count) => `${count} sticker${count > 1 ? "s" : ""} manquant${count > 1 ? "s" : ""}`,
    collectedOfTotalShort: (owned, total) => `${owned} sur ${total} collectés`,
    sinceDate: (date) => `depuis le ${date}`,
    albumPodium: "Podium de l’album",
    favouriteCards: "Mes cartes préférées",
    personalTopThree: "Top 3 personnel",
    mensRanking: "Classement hommes",
    mensRankingSubtitle: "Top 3 des équipes hommes par stickers collectés",
    womensRanking: "Classement femmes",
    womensRankingSubtitle: "Top 3 des équipes femmes par stickers collectés",
    comingTitle: "Bientôt sur la ligne de départ",
    comingAlt: "Cycliste gravissant une route de montagne",
    comingText: "Cette collection est au programme. Son suivi apparaîtra ici dès que le premier snapshot sera ajouté.",
  },
  countries: {
    AUS: "Australie", AUT: "Autriche", BEL: "Belgique", BRA: "Brésil",
    CAN: "Canada", COL: "Colombie", CZE: "Tchéquie", DEN: "Danemark",
    ECU: "Équateur", ERI: "Érythrée", ESP: "Espagne", FRA: "France",
    GBR: "Royaume-Uni", GER: "Allemagne", HUN: "Hongrie", IRL: "Irlande",
    ITA: "Italie", KAZ: "Kazakhstan", LAT: "Lettonie", LVA: "Lettonie",
    MEX: "Mexique", MRI: "Maurice", NED: "Pays-Bas", NOR: "Norvège",
    NZL: "Nouvelle-Zélande", POL: "Pologne", POR: "Portugal", SUI: "Suisse",
    SVN: "Slovénie", USA: "États-Unis",
  },
};

const englishText = {
  language: { label: "Language", french: "French", english: "English", pageTitle: "Panini Collection" },
  common: {
    loading: "Loading…",
    sticker: (count = 1) => `sticker${count === 1 ? "" : "s"}`,
    album: (count = 1) => `album${count === 1 ? "" : "s"}`,
    stickerFallback: (number) => `Sticker ${number}`,
    stickerNumber: (number) => `No. ${number}`,
    percentageCompleted: (percentage) => `${percentage}% complete`,
    countryLabel: (country) => `Country: ${country}`,
    collected: "Collected",
    missing: "Missing",
    obtainedOn: (date) => `Obtained on ${date}`,
    openAlbum: "View album",
    openFullSize: "View full-size image",
    fullSizeImage: "Full-size image",
    closeFullSize: "Close image",
  },
  navigation: {
    ariaLabel: "Tour de France albums",
    collection: "Collection",
    coming: "Coming soon",
    search: "Search the collection",
  },
  messages: {
    albumEyebrow: "Panini Album",
    collectionEyebrow: "Panini Collection",
    albumLoadError: "Unable to load the album",
    collectionLoadError: "Unable to load the collection",
    riderLoadError: "Unable to load the rider",
    countryLoadError: "Unable to load the country",
    albumIndexError: "Album index not found",
    snapshotsError: "No snapshots found",
    albumDataError: (title) => `Unable to load ${title}`,
  },
  search: {
    eyebrow: "Search",
    collectionEyebrow: "The whole collection",
    title: "Search for a sticker or country",
    intro: "Find a sticker by name or explore the riders from a country.",
    fieldLabel: "Sticker name or country",
    placeholder: "E.g. Pogačar or France",
    prompt: "Enter a name or country to get started.",
    noResults: (query) => `No stickers found for “${query}”.`,
    resultCount: (count) => `${count} result${count === 1 ? "" : "s"}`,
    albums: (count) => count === 1 ? "Album" : "Albums",
    albumOccurrence: (year, number) => `${year} (No. ${number})`,
    collectedCount: (count) => `${count} collected`,
    openLatestAlbum: "View latest album",
    country: "Country",
    countryStickerCount: (count) => `${count} rider sticker${count === 1 ? "" : "s"}`,
    openCountry: "View country",
  },
  rider: {
    eyebrow: "Rider profile",
    back: "Back to search",
    noAppearances: "No known appearances.",
    collectionStage: "In the collection",
    appearances: "Appearances",
    collectedOn: (date) => `Collected on ${date}`,
    favourite: "Favourite rider",
  },
  country: {
    eyebrow: "Country profile",
    back: "Back to collection",
    summary: (count) => `${count} rider sticker${count === 1 ? "" : "s"} in the collection`,
    noStickers: "No known rider stickers.",
    collectionStage: "In the collection",
    stickers: "Riders",
    picturesOnly: "With pictures only",
    noPictures: "No stickers with pictures for this country.",
  },
  collection: {
    eyebrow: "My Panini collection",
    title: "Tour de France",
    intro: "Every album, one finish line.",
    total: "overall",
    summaryLabel: "Collection summary",
    albums: "albums",
    completed: "completed",
    collected: "collected",
    missing: "missing",
    peloton: "The peloton",
    myAlbums: "My albums",
    equalWeight: "Every year counts equally",
    notStarted: "Not started",
    finishedOn: "Completed on",
    startedOn: "Started on",
    ownedOfTotal: (owned, total) => `${owned} of ${total} stickers`,
    openAlbum: "Open album",
    hallStage: "Hall of Fame",
    hallTitle: "All-time Top 10",
    selectedOfTen: (count) => `${count} of 10 selected`,
    emptyHallTitle: "The podium awaits its legends",
    emptyHallText: "Add up to 10 entries in",
  },
  export: {
    button: "PDF",
    collectedStickers: "Collected stickers",
    inventory: "Inventory",
    updates: "updates",
  },
  rankings: {
    nations: "The nations",
    countriesTitle: "Top 5 countries",
    countriesSubtitle: "Collected rider stickers",
    regulars: "The regulars",
    ridersTitle: "Top 5 across albums",
    ridersSubtitle: "Number of albums in which the rider is collected",
  },
  album: {
    completed: "complete",
    collectionStage: "Collection stage",
    collectedOfTotal: (owned, total) => `${owned} of ${total} stickers collected`,
    packetsOpened: (count) => `${count} packets opened`,
    start: "Start",
    finish: "Champs-Élysées",
    collectionHistory: "Collection progress",
    gainSince: (gain, date) => `${gain >= 0 ? "+" : ""}${gain} stickers since ${date}`,
    progressChartLabel: "Progress of collected sticker percentage",
    chartPoint: (date, percentage, owned, total) => `${date}: ${percentage}% (${owned} of ${total})`,
    lastUpdate: "Last updated",
    progress: "Progress",
    bestDay: "Best day",
    duplicatesHistory: "Duplicate progress",
    duplicatesLatest: (count) => `${count} duplicates in the latest snapshot`,
    duplicatesChartLabel: "Change in the number of duplicates",
    duplicatePoint: (date, count) => `${date}: ${count} duplicates`,
    currentDuplicates: "Current duplicates",
    sinceStart: "Since the start",
    duplicatesCount: (count) => `${count} duplicates`,
    yellowJersey: "Yellow jersey",
    inAlbum: "in the album",
    sprint: "Sprint",
    leftToChase: "left to chase",
    excludingInstants: (count) => `${count} excluding instant stickers`,
    mountain: "Mountains",
    duplicatesToTrade: "duplicates to trade",
    youngRider: "Young rider",
    markedFavourites: "marked favourites",
    chase: "Chasing",
    missingCount: (count) => `${count} missing sticker${count === 1 ? "" : "s"}`,
    collectedOfTotalShort: (owned, total) => `${owned} of ${total} collected`,
    sinceDate: (date) => `since ${date}`,
    albumPodium: "Album podium",
    favouriteCards: "My favourite cards",
    personalTopThree: "Personal top 3",
    mensRanking: "Men’s ranking",
    mensRankingSubtitle: "Top 3 men’s teams by collected stickers",
    womensRanking: "Women’s ranking",
    womensRankingSubtitle: "Top 3 women’s teams by collected stickers",
    comingTitle: "Coming to the start line soon",
    comingAlt: "Cyclist climbing a mountain road",
    comingText: "This collection is on the schedule. Tracking will appear here as soon as the first snapshot is added.",
  },
  countries: {
    AUS: "Australia", AUT: "Austria", BEL: "Belgium", BRA: "Brazil",
    CAN: "Canada", COL: "Colombia", CZE: "Czechia", DEN: "Denmark",
    ECU: "Ecuador", ERI: "Eritrea", ESP: "Spain", FRA: "France",
    GBR: "United Kingdom", GER: "Germany", HUN: "Hungary", IRL: "Ireland",
    ITA: "Italy", KAZ: "Kazakhstan", LAT: "Latvia", LVA: "Latvia",
    MEX: "Mexico", MRI: "Mauritius", NED: "Netherlands", NOR: "Norway",
    NZL: "New Zealand", POL: "Poland", POR: "Portugal", SUI: "Switzerland",
    SVN: "Slovenia", USA: "United States",
  },
};

export const supportedLanguages = ["fr", "en"];
export let uiText = frenchText;

export const setUiLanguage = (language) => {
  uiText = language === "en" ? englishText : frenchText;
};
